### ISSUE TITLE
Email pass is not strong 

### ISSUE THREAD

**Issue by saltsoftdrink** [StellarSand/IYPS#20]
It should show the password is weak if there is a email address as a password because most of the time I use same email as password for non personal account

**Comment by StellarSand** [comment]
> It should show the password is weak if there is a email address as a password

This won't be implemented/fixed due to the library's inability to accurately evaluate email addresses as passwords. Displaying a weak password solely based on the presence of an email will misrepresent crack times, guesses, and entropy, hence providing inaccurate results.

> I use same email as password for non personal account

Don't. **Do not** ever use your email as password even for non personal accounts. Email addresses are leaked easily, use [haveibeenpwned](https://haveibeenpwned.com) to assess the extent of potential breaches. Once an email is compromised, attackers can exploit it effortlessly by attempting the email in the password field, bypassing the need for dictionary matching, rainbow tables, or brute force attacks.
