### ISSUE TITLE
Entropy calculations wrong? 

### ISSUE THREAD

**Issue by mvevitsis** [StellarSand/IYPS#23]
### Description
I get wildly different results in this app compared to pazzword (also on fdroid) which uses zxcvbn. 

This app is reporting a 16 character randomly generated password (letters, numbers, symbols) as having only 56.47 bits of entropy which seems incredibly low to me. Pazzword reports 72.45 on the same password. Which frankly also seems wrong.

If I'm not mistaken the correct formula is 
E = L × log2(R)
A 16 character password using lower case, upper case, digits, and ASCII symbols should have a range  of 94, so:
E = 16 x log2(94)
E = 16 x 6.55
E = 104.8

### Steps to reproduce the behaviour
1. Enter password in both apps
2. Check entropy

**Comment by StellarSand** [comment]
- IYPS uses [zxcvbn4j](https://github.com/nulab/zxcvbn4j). Pazzword uses [nbvcxz](https://github.com/GoSimpleLLC/nbvcxz). 
nbvcxz itself states that [the results will be different](https://github.com/GoSimpleLLC/nbvcxz#compatibility) from the original [zxcvbn](https://github.com/dropbox/zxcvbn).
- IYPS calculates entropy from the estimated guesses needed to crack a password using `E = log2(guesses)`, since zxcvbn4j doesn't provide a direct way of getting the entropy.

BTW please don't expect same results between IYPS & any other app. If the goal was to display the exact same result, then I wouldn't have created this app as there's no point in duplicating an already existing project.
IYPS uses multiple additional password dictionaries alongside some of the default ones from zxcvbn4j.

Default dictionaries:
- [Female names](https://github.com/nulab/zxcvbn4j/blob/main/src/main/resources/com/nulabinc/zxcvbn/matchers/dictionaries/female_names.txt)	
- [Male names](https://github.com/nulab/zxcvbn4j/blob/main/src/main/resources/com/nulabinc/zxcvbn/matchers/dictionaries/male_names.txt)
- [Surnames](https://github.com/nulab/zxcvbn4j/blob/main/src/main/resources/com/nulabinc/zxcvbn/matchers/dictionaries/surnames.txt)
- [US TV and Film](https://github.com/nulab/zxcvbn4j/blob/main/src/main/resources/com/nulabinc/zxcvbn/matchers/dictionaries/us_tv_and_film.txt)

Additional:
- [Top 200 passwords of 2023](https://github.com/StellarSand/IYPS/blob/main/app/src/main/res/raw/top_200_2023_passwords.txt)
- [Common passwords](https://github.com/StellarSand/IYPS/blob/main/app/src/main/res/raw/other_common_passwords.txt)
- [English words](https://github.com/StellarSand/IYPS/blob/main/app/src/main/res/raw/english_words.txt)
- [Unranked words by EFF](https://github.com/StellarSand/IYPS/blob/main/app/src/main/res/raw/eff_unranked.txt)
- [Darkweb](https://github.com/StellarSand/IYPS/blob/main/app/src/main/res/raw/darkweb.txt)
- [French passwords](https://github.com/StellarSand/IYPS/blob/main/app/src/main/res/raw/richelieu_french.txt)
- [Unkown azul](https://github.com/StellarSand/IYPS/blob/main/app/src/main/res/raw/unkown_azul.txt)
