### ISSUE TITLE
FEATURE REQUEST: View additional information

### ISSUE THREAD

**Issue by Jackie7610** [StellarSand/IYPS#4]
Hi dev, 

I was wondering if a feature request like this could be accepted anytime later.

After creating a password some additional information like the number of combinations and the **exact** time needed to crack the password at _xxxx_ guess per second. The _‘xxxx’_ part if editable would be nice like 1000 guess/sec or 2310 guess/sec.

Thanks :)

**Comment by the-weird-aquarian** [comment]
> at xxxx guess per second

This may be implemented in the future, no promises though.

> exact time needed to crack the password

Password crack times are never exact and always will be "estimated" because of a number of variables-
1. Offline cracking:
   - Number of CPUs or CPU cores availables
   - Frequency of the CPU cores
   - Factors like temperatures which affect CPU frequency
   - Whether GPU is being used

 2. Online cracking:
    - CAPTCHAs
    - Network latency
    - Throttling

**Comment by StellarSand** [comment]
Since v1.4.0, I’ve included a substantial amount of additional information to be displayed and introduced several features & improvements. Unfortunately, making the guesses per second editable is currently not planned. As a result, I’m closing this issue. However, if I’m able to include this feature in the future, you’ll find it listed in the changelog.
